local Util = require("flexoki.util")

local M = {}

---@type flexoki.HighlightsFn
function M.get(c, opts)
  -- stylua: ignore
  return {
    Normal                      = { fg = c.fg, bg = opts.transparent and c.none or c.bg },
    NormalNC                    = { fg = c.fg, bg = opts.transparent and c.none or opts.dim_inactive and c.bg_dark or c.bg },
    NormalFloat                 = { fg = c.fg_float, bg = c.bg_float },
    NormalSB                    = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    ColorColumn                 = { bg = c.bg_dark },
    Conceal                     = { fg = c.dark5 },
    Cursor                      = { fg = c.bg, bg = c.fg },
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorColumn                = { bg = c.bg_highlight },
    CursorLine                  = { bg = c.bg_highlight },
    Directory                   = { fg = c.blue },
    EndOfBuffer                 = { fg = opts.transparent and c.none or c.bg },
    ErrorMsg                    = { fg = c.error },
    VertSplit                   = { fg = c.border },
    WinSeparator                = { fg = c.border },
    Folded                      = { fg = c.blue, bg = c.bg_dark },
    FoldColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.comment },
    SignColumn                  = { bg = opts.transparent and c.none or c.bg, fg = c.fg_gutter },
    SignColumnSB                = { bg = c.bg_sidebar, fg = c.fg_gutter },
    Substitute                  = { bg = c.red, fg = c.black },
    LineNr                      = { fg = c.fg_gutter },
    CursorLineNr                = { fg = c.orange, bold = true },
    LineNrAbove                 = { fg = c.fg_gutter },
    LineNrBelow                 = { fg = c.fg_gutter },
    MatchParen                  = { fg = c.orange, bold = true },
    ModeMsg                     = { fg = c.fg_dark, bold = true },
    MsgArea                     = { fg = c.fg_dark },
    MoreMsg                     = { fg = c.blue },
    NonText                     = { fg = c.dark3 },
    FloatBorder                 = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle                  = { fg = c.border_highlight, bg = c.bg_float, bold = true },
    Pmenu                       = { bg = c.bg_popup, fg = c.fg },
    PmenuKind                   = { fg = c.blue, bg = c.bg_popup },
    PmenuExtra                  = { fg = c.comment, bg = c.bg_popup },
    PmenuMatch                  = { bg = c.bg_popup, fg = c.blue1 },
    PmenuSel                    = { bg = c.bg_visual },
    PmenuKindSel                = { fg = c.blue1, bg = c.bg_visual },
    PmenuExtraSel               = { fg = c.comment, bg = c.bg_visual },
    PmenuMatchSel               = { fg = c.blue1, bg = c.bg_visual },
    PmenuSbar                   = { bg = c.bg_dark1 },
    PmenuThumb                  = { bg = c.fg_gutter },
    Question                    = { fg = c.blue },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.bg_search, fg = c.fg },
    IncSearch                   = { bg = c.orange, fg = c.black },
    CurSearch                   = "IncSearch",
    SpecialKey                  = { fg = c.dark3 },
    SpellBad                    = { sp = c.error, undercurl = true },
    SpellCap                    = { sp = c.warning, undercurl = true },
    SpellLocal                  = { sp = c.info, undercurl = true },
    SpellRare                   = { sp = c.hint, undercurl = true },
    StatusLine                  = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC                = { fg = c.fg_gutter, bg = c.bg_statusline },
    TabLine                     = { bg = c.bg_statusline, fg = c.fg_gutter },
    TabLineFill                 = { bg = opts.transparent and c.none or c.bg_dark },
    TabLineSel                  = { fg = c.black, bg = c.blue },
    Title                       = { fg = c.blue, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.warning },
    Whitespace                  = { fg = c.fg_gutter },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = "StatusLine",
    WinBarNC                    = "StatusLineNC",

    Boolean                     = { fg = c.orange },
    Bold                        = { bold = true, fg = c.fg },
    Character                   = { fg = c.green },
    Comment                     = { fg = c.comment, style = opts.styles.comments },
    Conditional                 = "Statement",
    Constant                    = { fg = c.orange },
    Debug                       = { fg = c.orange },
    Define                      = "PreProc",
    Delimiter                   = { fg = c.blue5 },
    Error                       = { fg = c.error },
    Exception                   = "Statement",
    Float                       = "Number",
    Function                    = { fg = c.blue, style = opts.styles.functions },
    Identifier                  = { fg = c.magenta, style = opts.styles.variables },
    Include                     = "PreProc",
    Italic                      = { italic = true, fg = c.fg },
    Keyword                     = { fg = c.cyan, style = opts.styles.keywords },
    Label                       = "Statement",
    Macro                       = "PreProc",
    Number                      = { fg = c.orange },
    Operator                    = { fg = c.blue5 },
    PreCondit                   = "PreProc",
    PreProc                     = { fg = c.cyan },
    Repeat                      = "Statement",
    Special                     = { fg = c.blue1 },
    SpecialChar                 = "Special",
    SpecialComment              = { fg = c.comment, style = opts.styles.comments },
    Statement                   = { fg = c.magenta },
    StorageClass                = "Type",
    String                      = { fg = c.green },
    Structure                   = "Type",
    Tag                         = "Special",
    Todo                        = { bg = c.todo, fg = c.black, bold = true },
    Type                        = { fg = c.blue1 },
    Typedef                     = "Type",
    Underlined                  = { fg = c.blue, underline = true },

    debugBreakpoint             = { bg = Util.blend_bg(c.info, 0.18), fg = c.info },
    debugPC                     = { bg = c.bg_sidebar },
    helpCommand                 = { bg = c.bg_dark, fg = c.blue },
    helpExample                 = { fg = c.comment },
    htmlH1                      = { fg = c.magenta, bold = true },
    htmlH2                      = { fg = c.blue, bold = true },
    qfFileName                  = { fg = c.blue },
    qfLineNr                    = { fg = c.dark5 },

    LspReferenceText            = { bg = c.bg_visual },
    LspReferenceRead            = { bg = c.bg_visual },
    LspReferenceWrite           = { bg = c.bg_visual },
    LspSignatureActiveParameter = { bg = c.bg_visual, bold = true },
    LspCodeLens                 = { fg = c.comment },
    LspInlayHint                = { bg = c.bg_dark, fg = c.dark5 },
    LspInfoBorder               = { fg = c.border_highlight, bg = c.bg_float },
    ComplHint                   = { fg = c.dark5 },

    DiagnosticError             = { fg = c.error },
    DiagnosticWarn              = { fg = c.warning },
    DiagnosticInfo              = { fg = c.info },
    DiagnosticHint              = { fg = c.hint },
    DiagnosticOk                = { fg = c.green },
    DiagnosticUnnecessary       = { fg = c.dark5 },
    DiagnosticVirtualTextError  = { bg = Util.blend_bg(c.error, 0.12), fg = c.error },
    DiagnosticVirtualTextWarn   = { bg = Util.blend_bg(c.warning, 0.12), fg = c.warning },
    DiagnosticVirtualTextInfo   = { bg = Util.blend_bg(c.info, 0.12), fg = c.info },
    DiagnosticVirtualTextHint   = { bg = Util.blend_bg(c.hint, 0.12), fg = c.hint },
    DiagnosticVirtualTextOk     = { bg = Util.blend_bg(c.green, 0.12), fg = c.green },
    DiagnosticUnderlineError    = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn     = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo     = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint     = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineOk       = { undercurl = true, sp = c.green },
    DiagnosticFloatingError     = "DiagnosticError",
    DiagnosticFloatingWarn      = "DiagnosticWarn",
    DiagnosticFloatingInfo      = "DiagnosticInfo",
    DiagnosticFloatingHint      = "DiagnosticHint",
    DiagnosticFloatingOk        = "DiagnosticOk",
    DiagnosticSignError         = "DiagnosticError",
    DiagnosticSignWarn          = "DiagnosticWarn",
    DiagnosticSignInfo          = "DiagnosticInfo",
    DiagnosticSignHint          = "DiagnosticHint",
    DiagnosticSignOk            = "DiagnosticOk",

    healthError                 = { fg = c.error },
    healthSuccess               = { fg = c.green },
    healthWarning               = { fg = c.warning },

    DiffAdd                     = { bg = c.diff.add },
    DiffChange                  = { bg = c.diff.change },
    DiffDelete                  = { bg = c.diff.delete },
    DiffText                    = { bg = c.diff.text },
    diffAdded                   = { bg = c.diff.add, fg = c.git.add },
    diffRemoved                 = { bg = c.diff.delete, fg = c.git.delete },
    diffChanged                 = { bg = c.diff.change, fg = c.git.change },
    diffOldFile                 = { fg = c.blue1, bg = c.diff.delete },
    diffNewFile                 = { fg = c.blue1, bg = c.diff.add },
    diffFile                    = { fg = c.blue },
    diffLine                    = { fg = c.comment },
    diffIndexLine               = { fg = c.magenta },
  }
end

return M
